### ISSUE TITLE
Error previous definitions on msm8996 in hardware-qcom-caf

### ISSUE THREAD

**Issue by FalconJaw** [ShapeShiftOS/android_hardware_qcom_display#1]
On compiling on Ubuntu 18.04 LTS
compiling in device with based SOC msm8996 msm8953 have this error
error: hardware/qcom-caf/msm8996/display/Android.bp:1:1: module "display_defaults" already defined
       hardware/qcom-caf/msm8998/display/Android.bp:1:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/Android.bp:19:1: module "display_headers" already defined
       hardware/qcom-caf/msm8998/display/Android.bp:19:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/Android.bp:36:1: module "display_intf_headers" already defined
       hardware/qcom-caf/msm8998/display/Android.bp:36:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/libqservice/Android.bp:1:1: module "libqservice" already defined
       hardware/qcom-caf/msm8998/display/libqservice/Android.bp:1:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/libqdutils/Android.bp:1:1: module "libqdutils" already defined
       hardware/qcom-caf/msm8998/display/libqdutils/Android.bp:1:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/libqdutils/Android.bp:22:1: module "libqdMetaData" already defined
       hardware/qcom-caf/msm8998/display/libqdutils/Android.bp:22:1 <-- previous definition here
error: hardware/qcom-caf/msm8996/display/libqdutils/Android.bp:34:1: module "libqdMetaData.system" already defined
       hardware/qcom-caf/msm8998/display/libqdutils/Android.bp:34:1 <-- previous definition here

**Comment by sashascurtu** [comment]
Adressed here https://github.com/ShapeShiftOS/android_manifest/commit/95ba75070cf7c50e4eaf8e11fee3efc3dc4251bc
